version: "{build}"

shallow_clone: true

environment:
  global:
    SEVENZIP: 'C:\Program Files\7-Zip\7z.exe'

before_build:
  - prepare_custom.bat

build_script:
  - '"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x86 /release'
  - make_all.bat
  - '"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64 /release'
  - make_all.bat

after_build:
  - if "%APPVEYOR_PULL_REQUEST_NUMBER%"=="" pack %APPVEYOR_REPO_COMMIT%

#test_script:
#  - 

artifacts:
  - path: pkg\*.zip
    name: main package
  - path: pkg\*_custom.7z
    name: custom package

# vim: ts=2 sw=2 et
